name: API tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
      - name: Save video
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-video
          path: cypress/videos
